baseURL = "https://comidistafoodie.com"
languageCode = "es-es"
title = "Comidistafoodie"
theme = "mediumish"
summaryLength = 25
copyright = "Comidistafoodie - All rights reserved"
#googleAnalytics = "UA-1XXXXXXX1-X"

[permalinks]
  reviews = '/:slug'
  static = '/:slug'
  noticias = '/:slug'

[params]
  logo = "/images/logo.png"
  description = "¡Te cuento lo que como!"
  mainSections = ['noticia', 'review']

[params.author]
  name = "Comidistafoodie"
  #thumbnail = "/images/author.jpg"
  description = "Comedor de esta web."

[params.social]
  instagram = "comidistafoodie"

## Main Menu
[[menu.main]]
    name = "Home"
    weight = 100
    identifier = "home"
    url = "/"
[[menu.main]]
    name = "Reviews"
    weight = 90
    identifier = "reviews"
    url = "/reviews"
[[menu.main]]
    name = "Noticias"
    weight = 90
    identifier = "noticias"
    url = "/noticias"
[[menu.main]]
    name = "Aviso Legal"
    weight = 80
    identifier = "aviso-legal"
    url = "/aviso-legal"
[[menu.main]]
    name = "Política de Cookies"
    weight = 80
    identifier = "politica-de-cookies"
    url = "/politica-de-cookies"
[[menu.main]]
    name = "Política de Privacidad"
    weight = 80
    identifier = "politica-de-privacidad"
    url = "/politica-de-privacidad"
